-- MySQL Script generated by MySQL Workbench
-- Tue Nov  7 13:36:36 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mctc_it
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mctc_it` ;

-- -----------------------------------------------------
-- Schema mctc_it
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mctc_it` DEFAULT CHARACTER SET utf8 ;
USE `mctc_it` ;

-- -----------------------------------------------------
-- Table `advisor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `advisor` ;

CREATE TABLE IF NOT EXISTS `advisor` (
  `idadvisor` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idadvisor`),
  UNIQUE INDEX `idadvisor_UNIQUE` (`idadvisor` ASC),
  UNIQUE INDEX `FirstName_UNIQUE` (`FirstName` ASC),
  UNIQUE INDEX `LastName_UNIQUE` (`LastName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `department` ;

CREATE TABLE IF NOT EXISTS `department` (
  `iddepartment` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddepartment`, `name`),
  UNIQUE INDEX `iddepartment_UNIQUE` (`iddepartment` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `faculty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `faculty` ;

CREATE TABLE IF NOT EXISTS `faculty` (
  `idFaculty` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `DepartmentId` INT(11) NOT NULL,
  PRIMARY KEY (`idFaculty`),
  UNIQUE INDEX `idFaculty_UNIQUE` (`idFaculty` ASC),
  INDEX `DepartmentId_idx` (`DepartmentId` ASC),
  CONSTRAINT `DepartmentId`
    FOREIGN KEY (`DepartmentId`)
    REFERENCES `department` (`iddepartment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `courses` ;

CREATE TABLE IF NOT EXISTS `courses` (
  `idcourses` INT(10) UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `section` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `maxStudents` INT(11) NULL DEFAULT NULL,
  `faculty_idFaculty` INT(11) NOT NULL,
  `faculty_DepartmentId` INT(11) NOT NULL,
  PRIMARY KEY (`idcourses`),
  UNIQUE INDEX `idcourses_UNIQUE` (`idcourses` ASC),
  INDEX `fk_courses_faculty1_idx` (`faculty_idFaculty` ASC, `faculty_DepartmentId` ASC),
  CONSTRAINT `fk_courses_faculty1`
    FOREIGN KEY (`faculty_idFaculty` , `faculty_DepartmentId`)
    REFERENCES `faculty` (`idFaculty` , `DepartmentId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `major`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `major` ;

CREATE TABLE IF NOT EXISTS `major` (
  `idmajor` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmajor`),
  UNIQUE INDEX `idmajor_UNIQUE` (`idmajor` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `students` ;

CREATE TABLE IF NOT EXISTS `students` (
  `idStudents` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `major_idmajor` INT(11) NOT NULL,
  `advisor_idadvisor` INT(11) NOT NULL,
  PRIMARY KEY (`idStudents`),
  UNIQUE INDEX `idStudents_UNIQUE` (`idStudents` ASC),
  INDEX `fk_students_major1_idx` (`major_idmajor` ASC),
  INDEX `fk_students_advisor1_idx` (`advisor_idadvisor` ASC),
  CONSTRAINT `fk_students_major1`
    FOREIGN KEY (`major_idmajor`)
    REFERENCES `major` (`idmajor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_students_advisor1`
    FOREIGN KEY (`advisor_idadvisor`)
    REFERENCES `advisor` (`idadvisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `transcript`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `transcript` ;

CREATE TABLE IF NOT EXISTS `transcript` (
  `StudentId` INT(11) NOT NULL,
  `Grade` VARCHAR(45) NULL DEFAULT NULL,
  `students_idStudents` INT(11) NOT NULL,
  `courses_idcourses` INT(10) UNSIGNED ZEROFILL NOT NULL,
  PRIMARY KEY (`StudentId`),
  INDEX `fk_transcript_students1_idx` (`students_idStudents` ASC),
  INDEX `fk_transcript_courses1_idx` (`courses_idcourses` ASC),
  CONSTRAINT `fk_transcript_students1`
    FOREIGN KEY (`students_idStudents`)
    REFERENCES `students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transcript_courses1`
    FOREIGN KEY (`courses_idcourses`)
    REFERENCES `courses` (`idcourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `courses_has_students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `courses_has_students` ;

CREATE TABLE IF NOT EXISTS `courses_has_students` (
  `courses_idcourses` INT(10) UNSIGNED ZEROFILL NOT NULL,
  `students_idStudents` INT(11) NOT NULL,
  INDEX `fk_courses_has_students_students1_idx` (`students_idStudents` ASC),
  INDEX `fk_courses_has_students_courses1_idx` (`courses_idcourses` ASC),
  CONSTRAINT `fk_courses_has_students_courses1`
    FOREIGN KEY (`courses_idcourses`)
    REFERENCES `courses` (`idcourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_has_students_students1`
    FOREIGN KEY (`students_idStudents`)
    REFERENCES `students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
